stages: 
  - test
  - build

services:
  - name: docker:20.10.21-dind
    command: ["--tls=false"]

variables:
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
  MAVEN_OPTS: >-
   -Dhttps.protocols=TLSv1.2
   -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
   -Dorg.slf4j.simpleLogger.showDateTime=true
   -Djava.awt.headless=true
  MAVEN_CLI_OPTS: >-
   --batch-mode
   --errors
   --fail-at-end
   --show-version
   --no-transfer-progress  

cache:
 paths:
   - .m2/repository

test:
  stage: test
  image: maven:3-eclipse-temurin-19
  script:
   - mvn test

build:
  stage: build
  image: docker:20.10.21
  
  before_script:
   - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  script:
    - docker build -t $DOCKER_IMAGE:$DOCKER_TAG .
    - docker push $DOCKER_IMAGE:$DOCKER_TAG